# PostgreSQL Bağlantı Ayarları
spring.datasource.url=jdbc:postgresql://localhost:5432/vardiya_devir
spring.datasource.username=postgres
spring.datasource.password=admin123

# JPA / Hibernate Ayarları
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# JSONB tipi uyumluluğu için (İleride esnek formlar için gerekecek)
spring.jpa.properties.hibernate.format_sql=true